//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Tracking_App.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Sales
    {
        public int SalesId { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<byte> Piece { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual TBL_Customer TBL_Customer { get; set; }
        public virtual TBL_Product TBL_Product { get; set; }
    }
}
